name: Deploy Admin to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login -u "oauth" --password-stdin registry.digitalocean.com

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/testcluster/test:v1.1 -f ./Dockerfile ./
          docker push registry.digitalocean.com/testcluster/test:v1.1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Install DigitalOcean CLI using Snap
      - name: Install DigitalOcean CLI with Snap
        run: |
          # Install Snap (if it's not already installed)
          sudo apt update
          sudo apt install -y snapd

          # Install doctl via Snap
          sudo snap install doctl

          # Connect the kube-config plug to allow access to the kube config
          sudo snap connect doctl:kube-config

          # Ensure the .kube directory exists
          mkdir -p $HOME/.kube

          # Verify installation
          doctl version

      # Authenticate with DigitalOcean
      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token "${{ secrets.DO_ACCESS_TOKEN }}"

      # **Step 1: Find and Delete Untagged Images**
      - name: Delete untagged images
        run: |
          REPO_NAME="testcluster"
          for DIGEST in $(doctl registry repository list-manifests $REPO_NAME --format Digest,Tags --no-header | awk '$2 == "" { print $1 }'); do
            echo "Deleting untagged image: $DIGEST"
            doctl registry repository delete-manifest $REPO_NAME --manifest-digest sha256:$DIGEST --force
          done

      # **Step 2: Run Garbage Collection**
      - name: Trigger Garbage Collection
        run: doctl registry garbage-collection start --include-untagged-manifests testcluster

      # Set Kubernetes Context
      - name: Set Kubernetes Context
        run: doctl kubernetes cluster kubeconfig save k8s-test-cluster

      # Restart Kubernetes Deployment
      - name: Restart Kubernetes Deployment
        run: kubectl rollout restart deployment test-deployment
