name: Deploy Admin to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login -u "oauth" --password-stdin registry.digitalocean.com

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.digitalocean.com/testcluster/test:v1.1 -f ./Dockerfile ./
          docker push registry.digitalocean.com/testcluster/test:v1.1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Install jq (used for parsing JSON)
      - name: Install jq
        run: sudo apt-get install jq

      # Get the latest release URL and Install DigitalOcean CLI
      - name: Install DigitalOcean CLI
        run: |
          # Get the latest release URL from GitHub API
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest | jq -r '.assets[] | select(.name | test("doctl-linux-amd64.tar.gz")) | .browser_download_url')

          # Check if the URL is set
          echo "Latest release URL: $LATEST_RELEASE"

          # Download and install doctl
          curl -sL $LATEST_RELEASE -o doctl.tar.gz
          tar -xzvf doctl.tar.gz
          sudo mv doctl /usr/local/bin/
          doctl version  # Verify installation

      # Authenticate with DigitalOcean
      - name: Authenticate with DigitalOcean
        run: doctl auth init --access-token "${{ secrets.DO_ACCESS_TOKEN }}"

      # Set Kubernetes Context
      - name: Set Kubernetes Context
        run: doctl kubernetes cluster kubeconfig save k8s-test-cluster

      # Restart Kubernetes Deployment
      - name: Restart Kubernetes Deployment
        run: kubectl rollout restart deployment test-deployment
